apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cproxy-issuer
spec:
  ca:
    secretName: cproxy-ca

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cproxy-ca
spec:
  isCA: true
  commonName: cproxy-ca
  secretName: cproxy-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cproxy-server-cert
spec:
  dnsNames:
    - cproxy
    - localhost
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    kind: Issuer
    name: cproxy-issuer
    group: cert-manager.io
  secretName: cproxy-server-cert 
